'use client'

import ButtonAppBar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box';
import Sidebar from '@/components/sidebar';
import { useState } from 'react'
import store from './store'
import { Provider } from 'react-redux'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(true);

  const onMenuClick = () => {
    setIsMenuOpen(prev => !prev);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
        <Box sx={{display: "flex"}}  className={!isMenuOpen ? "menu-open" : "menu-close"}>
          <Box>
            <Sidebar/>
          </Box>
          <Box width="100%">
            <ButtonAppBar onMenuClick={onMenuClick} />
            {children}
          </Box>
        </Box>
        </Provider>
      </body>
    </html>
  )
}
